### ISSUE TITLE
how to deal with rnastructure/6.3 test result

### ISSUE THREAD

**Issue by yshen16** [bu-rcs/PkgAutoTest#13]
the test directory: /share/pkg.8/rnastructure/6.3/test

This package contains a GUI application. And in the batch test,  I observed this special case - that is, the test.qsub.oxxxx output result is correct to show the test 'passed', but in test.qub.exxxx file, there will be a keyword 'ERROR' since it is for warning for being unable to make  a temporary directory which I believe was initiated by the process to try to open a DISPLAY at backend. 

So what is the protocol for GUI application? Do we need to address this issue? or we just ignore it, as long as the qsub output 'passed' for the test, we won't look at the error log.  Just record here for discussion in the next project meeting.

**Comment by bu-bgregor** [comment]
The keyword in the .e stderr file should be ignored by Nextflow, just the log file is used to count pass/fail numbers.  The last Nextflow run didn't tell us anything for this package as the test.qsub wasn't ready yet.  

The next full Nextflow run double-check this package.

**Comment by bu-bgregor** [comment]
New kill command in #18 should fix this problem.

**Comment by yshen16** [comment]
use the newly installed module pkgautotest/1.0 to test the module rnastructure/6.3 and now test passed beautifully. No error at all. The GUI process was ended by the autotest code gracefully.
