### ISSUE TITLE
Test drive draft instructions

### ISSUE THREAD

**Issue by aramp10** [bu-rcs/PkgAutoTest#16]
Action item from meeting notes:

- Andy - take the draft instructions for a test drive next week to see how it goes. The output of find_qsub.py can be cropped to the first 10 rows for expediency.

**Comment by aramp10** [comment]
### 1. Comments for "Step 1 - run find_qsub.py"
- Need a `module load python3` command to load Python, otherwise users may see a `ModuleNotFoundError: No module named 'tqdm'` error
- I had to use a `./` to precede calls for `find_qsub.py` (this may be a temporary fix until this workflow becomes its own module)
- The script worked but generated this error message:
```
less errors.log
SCC_STATA_DIR variable could not be determined for stata/18
```

### 2.  Comments for "Step 2 - Nextflow pipeline"
- Include a note to navigate to the "nextflow" subfolder. Similar to this sentence: The find_qsub.py script is located under the scripts directory. We could say: The pkgtest.nf script is located under the nextflow directory.
- I tried running my subset of 10 modules with nextflow and it generated some errors. I see the same when processing the `example.csv` file. I noticed that no jobs were submitted and I had to exit the terminal command with Ctrl-c. 
```
[11/1f33be] NOTE: Error submitting process 'runTests (openmpi/4.1.5_gnu-12.2.0)' for execution -- Error is ignored
[6a/afaa78] NOTE: Error submitting process 'runTests (openmpi/4.1.5_intel-2024)' for execution -- Error is ignored
[eb/3ba83a] NOTE: Error submitting process 'runTests (gdal/3.1.2)' for execution -- [e9/3e839b] process > runTests (openmpi/4.1.5_intel-2... [100%] 7 of 7, failed: 7
```

**Comment by bu-bgregor** [comment]
We looked at this during the 4/25 meeting, we were able to duplicate.

If nextflow runs with "--errorStrategy terminate" it'll print out the qsub error. Without this the error is still recorded in the .nextflow.log file. Example:

```
Apr-22 16:52:05.819 [Task submitter] INFO  nextflow.processor.TaskProcessor - [ea/11a318] NOTE: Error submitting process 'runTests (openmpi/4.1.5_nvidia-2023-23.5)' for execution -- Error is ignored
Apr-22 16:52:05.855 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - Failed to submit process runTests (openmpi/4.1.5_gnu-12.2.0) > exit: 5; workDir: /projectnb/rcstest/aramp10/PkgAutoTest/nextflow/work/11/1f33be297ccb738be7a64c09c1f9a1
qsub: Unknown option 

warning: "-P" option has already been set, overriding previous setting
```

so this is ok. In this case, the project name set by nextflow wasn't stored in the branch Andy used (main one), it can be spec'd with:

```
nextflow pkgtest.nf --csv_input module8_list.csv --project rcstest
```

**Comment by bu-bgregor** [comment]
Check out the develop branch:

```
git clone -b develop https://github.com/bu-rcs/PkgAutoTest.git
```

**Comment by aramp10** [comment]
SCC working directory:
`/projectnb/rcstest/aramp10/PkgAutoTest/`

I redid the test, this time I cloned from the develop branch. For the purposes of this quick test, I did filter out "imaging" modules since we already discussed these jobs running and not exiting.

I ran the test with 10 modules and the workflow appears to be running correctly. Nextflow kept track of the jobs as they were queued and completed. 

### Comment for "Step 3 - Review the results"

- Edit: the instructions said a "report_" prefix would be added, in this test the prefix is missing. My output file name: `module8_list_subset.csv`. This is the same name as the csv_input, so adding this prefix would be helpful.
- I looked at the output file and there a mix of those that passed/failed. Overall, it looks like the workflow for testing packages is working.

**Comment by aramp10** [comment]
A follow up comment regarding the "report_" prefix for the output file. This command works correctly:
nextflow pkgtest.nf --csv_input module8_list_subset.csv

But these commands create an output CSV without the "report_" prefix:
nextflow pkgtest.nf --csv_input ./module8_list_subset.csv
nextflow pkgtest.nf --csv_input ../scripts/module8_list_subset.csv
There must be something about how Nextflow parses the [--csv_input] option when a relative path is given

Quick fix: in the instructions, we can say "copy the module list file to the nextflow subfolder". Then it's clear that the pkgtest.nf and the csv_input are in the same location.
