### ISSUE TITLE
Basic submission script

### ISSUE THREAD

**Issue by bu-bgregor** [bu-rcs/PkgAutoTest#2]
Define a basic submission script to read the file from Issue #1 and submit jobs with all output going to a specified directory.

**Comment by yshen16** [comment]
majority of the module's test/ subdirectory contain a ['test.qsub', but the following three contains different qsub names: 
/share/pkg.8/amber/22/test/testMPI.qsub
/share/pkg.8/amber/22/test/testGPU.qsub
/share/pkg.8/spliceai/1.3.1/test/test_gpu.qsub

**Comment by yshen16** [comment]
my working directory: 
/projectnb/scv/yshen16/dev/git/PkgAutoTest

**Comment by bu-bgregor** [comment]
This is handled by Nextflow.
