### ISSUE TITLE
Investigate NextFlow to run the submission script and reporting script

### ISSUE THREAD

**Issue by bu-bgregor** [bu-rcs/PkgAutoTest#4]
What would this look like?  Easier/harder than using bash?  Especially with different environments (MPI, GPU, etc)?  

Task: sketch out what a Nextflow workflow script would look like...

**Comment by katgit** [comment]
@bu-bgregor @milechin 
I would add Yun and Andy to this discussion. Both spent some time learning NextFlow and may have some suggestions.

**Comment by bu-bgregor** [comment]
@katgit  - Github won't let me add Andy.

**Comment by milechin** [comment]
I scheduled a meeting with Andy for Friday, 3-4PM, to discuss/explore the feasibility to use Nextflow for our needs.

**Comment by milechin** [comment]
Andy and I discussed/investigated the potential use of Nextflow.  We were able to develop a simple protype that can be found here:

/projectnb/scv/milechin/nextflow

The files to run the pipeline are as follows (example output is available in directory above):

- input.csv - is the input file that contains the name/version of the module to be tested and the full path to the test.qsub file.
- example.nf - the nextflow pipeline script

To run the pipeline you will need to run the following commands:

```
module load nextflow
nextflow example.nf -with-report report.html
```

Nextflow process will generate the following items:
- report.html - Summary report of the pipeline that can be opened using firefox
- work - directory containing all the logs and files associated with each task.

Use firefox to open the report.html file and scroll down to the very bottom to the "Tasks" summary table to see the results of each test.

This script will only run the jobs on a local machine.  It does not submit jobs to the SCC yet, that is still a TODO item.  I can go into more detail about this workflow at the meeting tomorrow.

Below, I am also including some useful links:

1. Templating - https://www.nextflow.io/docs/latest/process.html#template

1. Abstraction of execution environment:

    - https://www.nextflow.io/docs/latest/basic.html#execution-abstraction
    - https://www.nextflow.io/docs/latest/executor.html

1. Execution log - https://www.nextflow.io/docs/latest/tracing.html#execution-log

1. Execution log report

   - https://www.nextflow.io/docs/latest/tracing.html#execution-report
   - https://www.nextflow.io/docs/latest/metrics.html
				   

1. Mail & Notification config: https://www.nextflow.io/docs/latest/mail.html

1. Apptainer Integration: https://www.nextflow.io/docs/latest/container.html#apptainer

1. Ignore error : https://www.nextflow.io/docs/latest/process.html#errorstrategy

1. tagging processes : https://www.nextflow.io/docs/latest/process.html#tag

1. run process per record in CSV
   - https://github.com/nextflow-io/patterns/blob/master/docs/process-per-csv-record.md
   - https://www.nextflow.io/docs/latest/operator.html#splitcsv

1. Recipes: https://github.com/nextflow-io/patterns

**Comment by bu-bgregor** [comment]
I added a prototype script to find test.qsub scripts (see issue 1), the output csv format I used is:

```
module_name,module_version,module_name/version,path_to_test.qsub
```

**Comment by yshen16** [comment]
I found this post, may be helpful for addressing assigning the right resource parameter for each job, https://bioinformatics.stackexchange.com/questions/18609/nextflow-dynamically-setting-resource-directives-for-a-process and how to set the 'dynamic computing resource', this article pointed to is: 
https://www.nextflow.io/docs/latest/process.html#dynamic-computing-resources

**Comment by bu-bgregor** [comment]
In the code nextflow/ folder look at the example_dynamic_clusterOptions.nf and input_new_params_clusterOptions.csv files. These use cluster options pulled from the test.qsub file and a dynamic process to let us set arbitrary per-test queue options.

**Comment by milechin** [comment]
I did more research on the reporting options that we have in Nextflow and the following are my findings:

1.) **So one can access the meta data for a completed workflow using the `nextflow log` command.**
https://www.nextflow.io/docs/latest/cli.html#log

One can also use the log command to specify what fields are shown (`-F` option) and combine that with a template ( `-t` option), you can generate a custom text or an HTML based reporting file.  Below is an example of one:
https://www.nextflow.io/blog/2019/easy-provenance-report.html

This is limited to using the Nextflow provided metrics.

2.) **Nextflow does support plugins to extend the functionality of Nextflow.  It would have to be written in Groovy programming language.**  
https://www.nextflow.io/docs/latest/plugins.html#writing-plugins

I think this approach will give us access to Workflow metadata that is described here:
https://nextflow.io/docs/edge/metadata.html#workflow-introspection

Another thing the plugin approach supports is access to Trace-Observers which can respond to certain events.  Here is a summary from the documentation:

"A trace observer in Nextflow is an entity that can listen and react to workflow events, such as when a workflow starts, a task completes, a file is published, etc. Several components in Nextflow, such as the execution report and DAG visualization, are implemented as trace observers."
https://www.nextflow.io/docs/latest/plugins.html#trace-observers

So maybe if a test fails, Nextflow would gather the appropriate log and information that can be used for debugging and put it in a central location.  Or maybe after completion, initiate a reporting step.

3.) **I looked up to see what plugins are available and I found two that might be of interest to us.**

- [nf-sqldb](https://github.com/nextflow-io/nf-sqldb) - This plugin allows interaction with SQL databases, including SQLite.  So there might be a way for us to consolidate all the information from Nextflow and the individual jobs into a SQLite file for post-run reporting.
- [nf-weblog](https://github.com/nextflow-io/nf-weblog) - This will send Nextflow metadata to an HTTP endpoint.  I don't know what useful HTTP endpoints we could use to log the data, but maybe one of you know.

We can discuss this some more at our next meeting.

-Dennis

**Comment by bu-bgregor** [comment]
We are going with Nextflow.
