### ISSUE TITLE
newpkg updates - doc symlink needs changing

### ISSUE THREAD

**Issue by bu-bgregor** [bu-rcs/PkgAutoTest#5]
With the modified newpkg, the doc symlink is not correct, it can just point to a `doc` directory created in the newpkg directory, i.e. `doc -> /share/pkg.8/newpkg/0.1.9/install/doc` .  That way we're not copying those 4 (or more, potentially) files all over /share/pkg.8 as we create modules.

**Comment by yshen16** [comment]
shall we then just put the doc in the 'test' folder as it is only for references for test purpose.

**Comment by yshen16** [comment]
done with this, made the following changes: 
1） make a new doc/
2) moved template_readme_xxx and template_bash_tests.txt to doc/
3. rename these files and removed 'template_' before the names.
4) modify 'newpkg' to simply the code to link to newpkg/doc dir in test/, so all the readme file will be a soft link in test/doc

clearn all the changes made previously that no longer are necessary.
