### ISSUE TITLE
SCC_NEWPKG_TESTDOC variable

### ISSUE THREAD

**Issue by bu-bgregor** [bu-rcs/PkgAutoTest#9]
Please add an environment variable, SCC_NEWPKG_TESTDOC, to the current newpkg modulefile. It will point to `/share/pkg.8/newpkg/0.1.9/install/doc`

Thanks!

**Comment by yshen16** [comment]
added since newpkg/0.1.9. Also reflected in newpkg/0.2.0 as well.
